CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    CREATEDAT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CHALLENGE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    STATUS BOOLEAN NOT NULL,
    GOAL VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS CHALLENGECUSTOMER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERID INT NOT NULL,
    CHALLENGEID INT NOT NULL,
    AMOUNT INT NOT NULL,
    STARTDATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    ENDDATE DATETIME,
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(ID),
    FOREIGN KEY (CHALLENGEID) REFERENCES CHALLENGE(ID)
);

CREATE TABLE IF NOT EXISTS MEASUREMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERID INT NOT NULL,
    CHALLENGEID INT NOT NULL,
    WEIGHT INT NOT NULL,
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(ID),
    FOREIGN KEY (CHALLENGEID) REFERENCES CHALLENGE(ID)
);

INSERT INTO CUSTOMER (NAME, EMAIL) VALUES
('Alice Johnson', 'alice.johnson@example.com'),
('Bob Smith', 'bob.smith@example.com'),
('Charlie Brown', 'charlie.brown@example.com');

INSERT INTO CHALLENGE (STATUS, GOAL) VALUES
(TRUE, 'Lose 5 kg'),
(TRUE, 'Run 100 km in a month'),
(FALSE, 'Drink 2L of water daily');

INSERT INTO CHALLENGECUSTOMER (CUSTOMERID, CHALLENGEID, AMOUNT, STARTDATE, ENDDATE) VALUES
(1, 1, 5, '2025-04-01', '2025-05-01'),
(2, 2, 100, '2025-04-10', '2025-05-10'),
(3, 3, 60, '2025-03-15', '2025-04-15');

INSERT INTO MEASUREMENT (CUSTOMERID, CHALLENGEID, WEIGHT) VALUES
(1, 1, 72),
(1, 1, 70),
(2, 2, 80),
(2, 2, 78),
(3, 3, 90),
(3, 3, 88);

SELECT
    cu.ID AS CustomerID,
    cu.NAME AS CustomerName,
    cu.EMAIL,
    cu.CREATEDAT AS CustomerCreatedAt,

    ch.ID AS ChallengeID,
    ch.STATUS AS ChallengeStatus,
    ch.GOAL AS ChallengeGoal,

    cc.AMOUNT,
    cc.STARTDATE,
    cc.ENDDATE,

    m.WEIGHT,
    m.ID AS MeasurementID

FROM CUSTOMER cu
JOIN CHALLENGECUSTOMER cc ON cu.ID = cc.CUSTOMERID
JOIN CHALLENGE ch ON ch.ID = cc.CHALLENGEID
LEFT JOIN MEASUREMENT m ON cu.ID = m.CUSTOMERID AND ch.ID = m.CHALLENGEID
ORDER BY cu.ID, ch.ID, m.ID;